name: Request C3 Project Space
description: "Request a workspace for a C3 DTI application suite."
#labels: []
body:
  - type: markdown
    attributes:
      value: |
        Reqest form for a dedicated development space.  Developers requesting a dedicated space should already have a 
        working application package in the DTI shared development space.
  - type: input
    id: tenant
    attributes:
      label: Primary package/application short-name
      description: | 
        A short name for the primary application.  No more than 16 characters.  
        No specal characters (dashes allows, no underscore).  All lowercase.
      placeholder: ex. storm-tracker
    validations:
      required: true
  - type: input
    id: space
    attributes:
      label: Application repository short-name
      description: | 
        A short name for the application repository that will contain your primary application.  
        No more than 16 characters.  No specal characters (dashes allows, no underscore).  
        All lowercase.
      placeholder: ex. storm-apps
    validations:
      required: true
  - type: input
    id: current-package
    attributes:
      label: Current package/application name
      description: The package name for your current application.
    validations:
      required: true
  - type: dropdown
    id: current-space
    attributes:
      label: Current shared development space.
      description: The current location for shared development of the above package.
      options:
        - training-space-IDS (dti-jupyter, dev on TC1)
    validations:
      required: true


    
    
